### PR TITLE
Haskell-CI for GHC 8.4.4 to 9.4.4

### LINKED ISSUE #8: monadplus 1.4.3 fails to build with GHC <= 8.2
With GHC 8.2 and 8.0 we get the error reported in #7:
```
src/Control/Monad/Plus.hs:270:15: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Sem.<>’,
                             imported from ‘Data.Semigroup’ at src/Control/Monad/Plus.hs:67:1-28
                          or ‘Data.Monoid.<>’,
                             imported from ‘Data.Monoid’ at src/Control/Monad/Plus.hs:68:1-18
```
With GHC 7.10 and 7.8 I see:
```
src/Control/Monad/Plus.hs:67:8:
    Could not find module ‘Data.Semigroup’
```

So, it looks like `monadplus-1.4.3` is for GHC 8.4 only and this should be reflected in bound `base >= 4.11`.

In my role as Hackage Trustee, I corrected the `base` bound in a revision: https://hackage.haskell.org/package/monadplus-1.4.3/revisions/

However, this bound should also be fixed in the codebase here, to avoid regressions.

This issue superseds the following which can be closed:
- #7

### LINKED ISSUE #9: Does this repo contain the changes for 1.4.3?
The repo has 1.4.2:
https://github.com/hanshoglund/monadplus/blob/7f1bfd12f66c33db503c6ff0b4f6965681d95c8d/monadplus.cabal#L2-L3

However, hackage has 1.4.3 and points to this repository.

Ollie @ocharles, where are the latest sources hosted if not here?  
(Or maybe you didn't merge the changes in here yet.  In this case, please do so, so that you can receive contributions.)
(Or is just the version bump not committed yet?)

### PR DESCRIPTION
**Pull request by andreasabel**
This PR contributes a standard CI generated with Haskell-CI.  It tests build with GHC 8.4.4 to 9.4.4 (latest minor releases).
Successful run here: https://github.com/andreasabel/monadplus/actions/runs/3917714388/jobs/6697676450

CI will kick in on this repo once you merge this PR into `master`.

This PR also has commits addressing these issues:
- fix #8 (`base` bump)
- fix #9 (`version` bump`)

### CODE REVIEW

**Comment by andreasabel** [comment]
@ocharles : I fixed the conflicts with `master`.

**Comment by ocharles** [comment]
Thanks, this LGTM! I'm not very familiar with Haskell-CI, but it all seems to pass so it's good enough for me!

**Comment by andreasabel** [comment]
The merging broke the `cabal check` in the CI.

Fixup: 
- #12
