### ISSUE TITLE
monadplus 1.4.3 fails to build with GHC <= 8.2

### ISSUE THREAD

**Issue by andreasabel** [hanshoglund/monadplus#8]
With GHC 8.2 and 8.0 we get the error reported in #7:
```
src/Control/Monad/Plus.hs:270:15: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Sem.<>’,
                             imported from ‘Data.Semigroup’ at src/Control/Monad/Plus.hs:67:1-28
                          or ‘Data.Monoid.<>’,
                             imported from ‘Data.Monoid’ at src/Control/Monad/Plus.hs:68:1-18
```
With GHC 7.10 and 7.8 I see:
```
src/Control/Monad/Plus.hs:67:8:
    Could not find module ‘Data.Semigroup’
```

So, it looks like `monadplus-1.4.3` is for GHC 8.4 only and this should be reflected in bound `base >= 4.11`.

In my role as Hackage Trustee, I corrected the `base` bound in a revision: https://hackage.haskell.org/package/monadplus-1.4.3/revisions/

However, this bound should also be fixed in the codebase here, to avoid regressions.

This issue superseds the following which can be closed:
- #7
