### ISSUE TITLE
Latest monadplus (1.4.2) has build failure with GHC 8.4-9.4

### ISSUE THREAD

**Issue by andreasabel** [hanshoglund/monadplus#6]
The _latest_ GHC monadplus-1.4.2 builds with is GHC 8.2.2 (base-4.10).
@ocharles : I do not understand why you removed bound `base < 4.11` in your revision: https://hackage.haskell.org/package/monadplus-1.4.2/revisions/
This bound was correct.

```console
$ cabal build
...
Build profile: -w ghc-9.4.4 -O1
...
Building library for monadplus-1.4.2..
...
[2 of 2] Compiling Control.Monad.Plus ( src/Control/Monad/Plus.hs, /Users/abel/tmp/monadplus-1.4.2/dist-newstyle/build/x86_64-osx/ghc-9.4.4/monadplus-1.4.2/build/Control/Monad/Plus.o, /Users/abel/tmp/monadplus-1.4.2/dist-newstyle/build/x86_64-osx/ghc-9.4.4/monadplus-1.4.2/build/Control/Monad/Plus.dyn_o )

src/Control/Monad/Plus.hs:256:10: error:
    • No instance for (Semigroup (Partial a b))
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid (Partial a b)’
    |
256 | instance Monoid (Partial a b) where
    |          ^^^^^^^^^^^^^^^^^^^^
Error: cabal: Failed to build monadplus-1.4.2.
```

**Comment by ocharles** [comment]
Thanks for the report @andreasabel. I removed that because of this instance exists in the code tracked in Git (https://github.com/hanshoglund/monadplus/blob/master/src/Control/Monad/Plus.hs#L265) and I erroneously concluded it was released. I'll restore that revision and cut a proper release.

**Comment by ocharles** [comment]
I think this should now be fixed. Chuck me a reply here if I've still left things broken!

**Comment by andreasabel** [comment]
Looks fine!
